export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const SET_COMMENTS_SYNC = 'SET_COMMENTS_SYNC';
export const SET_REPLYING_TO = 'SET_REPLYING_TO';
export const SET_SENDING_COMMENT = 'SET_SENDING_COMMENT';
export const SET_POLLING_COMMENTS = 'SET_POLLING_COMMENTS';
