const ADD_COMMENT = 'ADD_COMMENT';
const ADD_REPLY = 'ADD_REPLY';
const DELETE_COMMENT = 'DELETE_COMMENT';
const SET_REPLYING_TO = 'SET_REPLYING_TO';

export {
  ADD_COMMENT,
  ADD_REPLY,
  DELETE_COMMENT,
  SET_REPLYING_TO,
};
